spring:
  config:
    activate:
      on-profile: db
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
    username: apiuser
    password: apipassword
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
