spring:
#  hazelcast:
#    config: classpath:hazelcast.yml
  profiles:
    active: "db"

server:
  port: 8080

#logging:
#  level:
#    com:
#      hazelcast: DEBUG

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      jvm: true
  health:
    binders:
      enabled: false
    ldap:
      enabled: false
